#use_frameworks!

install!'cocoapods',
:deterministic_uuids => false,
:warn_for_unused_master_specs_repo => false

platform :ios, '10.0'

target 'Libffi_iOS_Example' do
  pod 'ZDLibffi', :path => '../'

  target 'Libffi_iOS_Tests' do
    inherit! :search_paths

    
  end
end
