# lint
name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '*'

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  Lint:
    name: Pod Lib Lint
    runs-on: macos-15
    # https://github.com/SDWebImage/SDWebImage/blob/master/.github/workflows/CI.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Pod Update
        run: pod update --project-directory=./Example

      - name: Run Podsepec Lint
        run: |
          set -o pipefail
          pod lib lint ZDLibffi.podspec --allow-warnings --platforms=ios,macos --skip-tests
          pod lib lint ZDLibffi.podspec --allow-warnings --platforms=ios,macos --use-modular-headers --skip-tests

  SPM:
    name: SPM Build
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Package.swift
        run: swift package describe

      - name: Build with SwiftPM
        run: swift build
